In [2]:
import numpy as np

### 7-1. 실습 예제 1~3

In [4]:
# 예제 1 : 원소가 모두 3인 (3,4,5) 형태의 numpy.array 출력
arr = np.full((3,4,5), 3)
print(arr)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [8]:
# 예제 2 : 정수 -50~50 사이의 난수 (4,5)형태 정렬
arr = np.random.randint(-50, 50, (4, 5))
# array 작성
print(arr)
# 행을 기준으로 오름차 정렬
print(np.sort(arr, axis=0))
# 1차원 배열로 정렬
print(np.sort(arr, axis=None))

[[ 48 -50 -46  19  31]
 [ 15 -48  29  -6 -32]
 [ 30  -9 -43  20   6]
 [-30  45 -31 -47 -25]]
[[-30 -50 -46 -47 -32]
 [ 15 -48 -43  -6 -25]
 [ 30  -9 -31  19   6]
 [ 48  45  29  20  31]]
[-50 -48 -47 -46 -43 -32 -31 -30 -25  -9  -6   6  15  19  20  29  30  31
  45  48]


In [11]:
# 예제 3 : 연산
py_list = [np.full(3,8),
          np.array([33, -15, 26]),
          np.linspace(17, 26, 3)
          ]

# 각 array들의 원소의 평균값
result_arr = []
for i in py_list:
    result_arr.append(np.mean(i))
    result_arr.append(np.std(i))
    result_arr.append(np.median(i))
    
print(result_arr)

[8.0, 0.0, 8.0, 14.666666666666666, 21.171259344267224, 26.0, 21.5, 3.6742346141747673, 21.5]


### 7-2. 실습 예제 4~6

In [12]:
# 예제 4번 : 분할 후 제곱하여 병합
arr = np.arange(2, 20, 2). reshape((3, 3))
s1 = np.vsplit(arr, 3)
s2 = np.square(s1)
s3 = np.squeeze(s2, axis=1)
result_arr = np.vstack((arr, s3))
print(result_arr)

[[  2   4   6]
 [  8  10  12]
 [ 14  16  18]
 [  4  16  36]
 [ 64 100 144]
 [196 256 324]]


In [16]:
# 예제 5 : 삼각함수 특수각 
arr = np.arange(0, 91, 30)
lst = []
lst.append(np.sin(arr * np.pi / 180)) # radian 값으로 변환
lst.append(np.cos(arr * np.pi / 180))
lst.append(np.tan(arr * np.pi / 180))

for value_lst in lst:
    for value in value_lst:
        if value > 99999999:
            print("INF")
            continue
        print(value)
    print()

0.0
0.49999999999999994
0.8660254037844386
1.0

1.0
0.8660254037844387
0.5000000000000001
6.123233995736766e-17

0.0
0.5773502691896256
1.7320508075688767
INF



In [22]:
# 예제 6 : 체크 패턴 출력
arr = np.zeros((7, 7), dtype=int)
arr[::2, 1::2] = 1 # 0행부터 끝행까지 2스텝, 1열부터 2스텝씩
arr[1::2, ::2] = 1 # 1행부터 끝행까지 2스텝, 0열부터 2스텝씩

for row in range(7):
    for col in range(7):
        print(arr[row, col], end=" ")
    print()

0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
