# 2-1. 배열의 index 접근하기

In [2]:
import numpy as np

In [10]:
# 1차원 배열 indexing ( index는 0부터 )
arr = np.arange(10)
print(arr[7], arr[-2], arr[:4])

7 8 [0 1 2 3]


In [17]:
# 2차원 배열 indexing 
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0][2], arr[0, :3]) # 0행 2열, 0행 0~2열까지

3 [1 2 3]


# 2-2. Fancy Indexing
특정 인덱스를 여러개 선택해서 탐색

In [18]:
# 1차원 배열 fancy indexing -> [[]] 사용
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[[0,2,3]])

[ 5 15 20]


In [21]:
# 2차원 배열 fancy indexing 
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[[0,2], 2:]) # 0~1행 2열부터
print(arr[1:, [2,3]]) # 1행부터 2,3열 

[[ 3  4]
 [11 12]] [[ 7  8]
 [11 12]]


# 2-3. Boolean Indexing 

In [22]:
arr = np.array([1,2,3,4])
print(arr[[True,False,True,True]]) # True에 해당하는 값만 가져옴

[1 3 4]


In [23]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
print(arr[[True,False], True]) # 0행만 전부 가져옴

[[1 2 3 4]]


In [25]:
# 조건 연산자로 값 가져오기 ( 아예 풀어서 가져옴 )
print(arr[arr>3])

[4 5 6 7 8]
