In [5]:
import numpy as np

# 3-1. 사칙연산 / 제곱 / 제곱근 / 몫/ 나머지
배열 간의 연산 -> 기본적으로는 shape이 같아야 함

In [2]:
arr1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

arr2 = np.array([[2,2,2],
               [2,2,2],
               [2,2,2]])

In [4]:
# 덧셈
# print(arr1+arr2)
print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
# 뺄셈
# print(arr1-arr2)
print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [6]:
# 곱셈 ( 원소 단위의 곱셈 ! 내적곱셈 X )
# print(arr1*arr2)
print(np.multiply(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
# 나눗셈
# print(arr1/arr2)
print(np.divide(arr1,arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [8]:
# 제곱
print(arr1**4)
# print(np.square(arr1))

[[   1   16   81]
 [ 256  625 1296]
 [2401 4096 6561]]


In [9]:
# 제곱근
print(np.sqrt(arr1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [11]:
# 몫
print(arr1//arr2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]


In [12]:
# 나머지
print(arr1%arr2)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


# 3-2. 내적( Dot Product ) / 절댓값 / 올림 / 내림 / 반올림 / 버림
내적 -> 두 행렬을 곱한 결과 값을 더해 스칼라가 되도록 하는 것 ( 차원을 한 단계 낮춤 )

In [6]:
# 1차원 행렬 내적
arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])
print(np.dot(arr1,arr2))

20


In [7]:
# 2차원 행렬 내적
'''
[[a,b],   [[e,f],    ->  [[ae+bg, af+bh],
 [c,d]] *  [g,h]]    ->   [ce+dg, cf+dh]]
'''
arr1 = np.array([[1,2],
                [4,5]])
arr2 = np.array([[1,2],
                [0,3]])
print(np.dot(arr1,arr2))

[[ 1  8]
 [ 4 23]]


In [8]:
# 절댓값 
arr = np.array([[1,-2],
                [-4,5]])
print(np.abs(arr1))

[[1 2]
 [4 5]]


In [9]:
# 올림 
arr1 = np.array([[1.932, -2.339],
               [-4.145, 5.206]])
print(np.ceil(arr1))

[[ 2. -2.]
 [-4.  6.]]


In [10]:
# 내림
print(np.floor(arr1))

[[ 1. -3.]
 [-5.  5.]]


In [11]:
# 반올림 
print(np.round(arr1))

[[ 2. -2.]
 [-4.  5.]]


In [12]:
# 버림
print(np.trunc(arr1))

[[ 1. -2.]
 [-4.  5.]]


# 3-3. 